[package]
name = "kanjikan-app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
gloo-utils = "0.1.5"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Document",
    "Element",
    "History",
    "HtmlElement",
    "Location",
    "Node",
    "Window",
]
